apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: odoo
  namespace: default
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  project: default
  source:
    chart: odoo
    helm:
      values: |
        pushgateway:
          enabled: false
    repoURL: https://charts.bitnami.com/bitnami
    targetRevision: 20.1.4
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
